Amalitech_Project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from Amalitech_Project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('video/', include('VideoApp.url')),
    path('account/', include('account.url')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VideoApp/models.py
import uuid

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

#userProfile Model
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    verified = models.BooleanField(default=True)

    def __str__(self):  # Corrected method name to '__str__' instead of 'str'
        return self.user.username

class Video(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=100)
    description = models.TextField()
    uploaded_by = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    file = models.FileField(upload_to='media/video/')
    created_at = models.DateTimeField(auto_now_add=True)
    video_link = models.URLField()

    def save(self, *args, **kwargs):
        self.video_link = self.file.url  # Automatically sets video_link to the URL of the uploaded video file
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.title} - {self.description}"

    # def get_shareable_link(self):
    #     return reverse('video_detail', kwargs={'pk': self.pk})

templates/matrix-admin/All_Videos_Page.html
{% extends 'matrix-admin/index2.html' %}
{% block contents %}
<div class="container p-5 px-5">
    <h2 class="font-weight-bold mt-3">Video Page</h2>
    {% for message in messages %}
        <h2 class="mdi-message-alert error">{{ message }}</h2>
    {% endfor %}
    <h1>{{ video.title }}</h1>
    <div style="width: 100%; max-width: 800px;"> <!-- Adjust frame size as needed -->
        <video controls style="width: 100%;">
            <source src="{{ video.file.url }}" type="{{ video.file.content_type }}">
            Your browser does not support the video tag.
        </video>
    </div>
    <p>{{ video.description }}</p>
    <p>Share Video using the link: <a href="{% url 'admin_all_videos'  %}{{ video.id }}">Get Link</a></p>

  {% if previous_video %}
    <form action="{% url 'next_video' previous_video.pk %}" method="get">
        <button type="submit">Previous</button>
    </form>
{% endif %}

{% if next_video %}
    <form action="{% url 'next_video' next_video.pk %}" method="get">
        <button type="submit">Next</button>
    </form>
{% else %}
    <p>No more videos</p>
{% endif %}
</div>
{% endblock contents %}

templates/matrix-admin/Upload_Video.html
{% extends 'matrix-admin/index2.html' %}
{% load crispy_forms_filters %}
{% block contents %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <h2 class="font-weight-bold mb-0">Upload Video</h2>
                    {% for message in messages%}
                       <h3> {{ message }}</h3>
                    {% endfor %}
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form|crispy }}
                        </div>
                        <button type="submit" class="btn btn-primary">Upload</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}

templates/matrix-admin/authentication-login.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!-- Favicon icon -->
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="dashboard/images/favicon.png"
    />
    <title>Rift Video Login</title>
    <!-- Custom CSS -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="main-wrapper">
      <!-- ============================================================== -->
      <!-- Preloader - style you can find in spinners.css -->
      <!-- ============================================================== -->
      <div class="preloader">
        <div class="lds-ripple">
          <div class="lds-pos"></div>
          <div class="lds-pos"></div>
        </div>
      </div>
      <!-- ============================================================== -->
      <!-- Preloader - style you can find in spinners.css -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Login box.scss -->
      <!-- ============================================================== -->
      <div
        class="auth-wrapper d-flex no-block justify-content-center align-items-center bg-dark"
      >
        <div class="auth-box bg-dark border-top border-secondary">
          <div id="loginform1">
            <div class="text-center p-t-20 p-b-20">
              <span class="db"
                ><img src="{% static 'images/logo-icon.png' %}" alt="logo"
              /></span>
            </div>
            <!-- Backend Messages -->
            {% for message in messages %} {{message}} {% endfor %}
            <!-- Form -->
           <form class="form-horizontal m-t-20" id="loginform" action="{% url 'index' %}" method="post">
    {% csrf_token %}
    <div class="row p-b-30">
        <div class="col-12">
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-success text-white" id="basic-addon1">
                        <i class="ti-user"></i>
                    </span>
                </div>
                <input type="email" class="form-control form-control-lg" name="email" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1" required="">
            </div>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text bg-warning text-white" id="basic-addon2">
                        <i class="ti-pencil"></i>
                    </span>
                </div>
                <input type="password" class="form-control form-control-lg" name="password" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" required="">
            </div>
        </div>
                  
                <div class="col-12">
                  <div class="form-group">
                    <div class="p-t-20">
                      <a href="{% url 'forget_password' %}">Forgot Password</a>
                        <br>
                      <a href="{% url 'register' %}">Don't Have an Account? Register</a>
                      <button class="btn btn-success float-right" type="submit">
                        Login
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
         
          
    
          </div>
        </div>
      </div>
      <!-- ============================================================== -->
      <!-- Login box.scss -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Page wrapper scss in scafholding.scss -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Page wrapper scss in scafholding.scss -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Right Sidebar -->
      <!-- ============================================================== -->
      <!-- ============================================================== -->
      <!-- Right Sidebar -->
      <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
      $('[data-toggle="tooltip"]').tooltip();
      $(".preloader").fadeOut();
      // ==============================================================
      // Login and Recover Password
      // ==============================================================
      $("#to-recover").on("click", function () {
        $("#loginform").slideUp();
        $("#recoverform").fadeIn();
      });
      $("#to-login").click(function () {
        $("#recoverform").hide();
        $("#loginform").fadeIn();
      });
    </script>
  </body>
</html>

templates/matrix-admin/authentication-register.html
{% load static %}
<!DOCTYPE html>
<html >

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon.png' %}">
    <title>Rift SignUp</title>
    <!-- Custom CSS -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <div class="main-wrapper">
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <div class="preloader">
            <div class="lds-ripple">
                <div class="lds-pos"></div>
                <div class="lds-pos"></div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Preloader - style you can find in spinners.css -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <div class="auth-wrapper d-flex no-block justify-content-center align-items-center bg-dark">
            <div class="auth-box bg-dark border-top border-secondary">
                <div>
                    <div class="text-center p-t-20 p-b-20">
                        <span class="db"><img src="{% static 'images/logo.png' %}" alt="logo" /></span>
                    </div>
                    <div class="text-center p-t-20 p-b-20">
                      <h3>
                        {% for message in messages %}
                        {{message}}
                       {% endfor %}
                      </h3>
                        
                    </div>
                   
                
                    <!-- Form -->
                    <form class="form-horizontal m-t-20" action="" method="post">
                        {% csrf_token %}
                        <div class="row p-b-30">
                            <div class="col-12">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-success text-white" id="basic-addon1"><i class="ti-user"></i></span>
                                    </div>
                                    <input type="text" class="form-control form-control-lg" name="username" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1" required>
                                </div>
                                <!-- email -->
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-danger text-white" id="basic-addon1"><i class="ti-email"></i></span>
                                    </div>
                                    <input type="email" class="form-control form-control-lg" name="email" placeholder="Email Address" aria-label="Username" aria-describedby="basic-addon1" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-warning text-white" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="password" class="form-control form-control-lg" name="password" placeholder="Password" aria-label="Password" aria-describedby="basic-addon1" required>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text bg-info text-white" id="basic-addon2"><i class="ti-pencil"></i></span>
                                    </div>
                                    <input type="password" class="form-control form-control-lg" name="password2" placeholder=" Confirm Password" aria-label="Password" aria-describedby="basic-addon1" required>
                                </div>
                            </div>
                        </div>
                        <div class="row border-top border-secondary">
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="p-t-20">
                                        <button class="btn btn-block btn-lg btn-info" type="submit">Sign Up</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                  <h3>Already Have An Account</h3>
                    <div class="p-t-20">
                     <a href="{% url 'index' %}" class="btn btn-block btn-lg btn-info">Login</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- ============================================================== -->
        <!-- Login box.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper scss in scafholding.scss -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Right Sidebar -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- All Required js -->
    <!-- ============================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ============================================================== -->
    <!-- This page plugin js -->
    <!-- ============================================================== -->
    <script>
    $('[data-toggle="tooltip"]').tooltip();
    $(".preloader").fadeOut();
    </script>
</body>

</html>

templates/matrix-admin/charts.html
{% load static %}
<!DOCTYPE html>
<html dir="ltr" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{ % static 'images/favicon.png' %}">
    <title>Rift Dashboard</title>
    <!-- Custom CSS -->
    <link href="{% static 'css/float-chart.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="lds-ripple">
            <div class="lds-pos"></div>
            <div class="lds-pos"></div>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
      
     
    
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <!-- Chart-1 -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Real Time Chart</h5>
                                 <div id="real-time" style="height:400px;"></div>
                                <p>Time between updates:
                                    <input id="updateInterval" type="text" value="" style="text-align: right; width:5em"> milliseconds
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- ENd chart-1 -->
                            
                <!-- Chart-3 -->
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Bar Chart</h5>
                                <div class="flot-chart">
                                    <div class="flot-chart-content" id="flot-line-chart"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
       

            <footer class="footer text-center">
               <h3>Rift Systems</h3>
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
  
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'libs/popper.js/dist/umd/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{% static 'libs/perfect-scrollbar/dist/perfect-scrollbar.jquery.min.js' %}"></script>
    <script src="{% static 'js/sparkline.js' %}"></script>
    <!--Wave Effects -->
    <script src="{% static 'js/waves.js' %}"></script>
    <!--Menu sidebar -->
    <script src="{% static 'js/sidebarmenu.js' %}"></script>
    <!--Custom JavaScript -->
    <script src="{% static 'js/custom.min.js' %}"></script>
    <!-- this page js -->
    <script src="{% static 'libs/chart/matrix.interface.js' %}"></script>
    <script src="{% static 'libs/chart/excanvas.min.js' %}"></script>
    <script src="{% static 'js/jquery.flot.js' %}"></script>
    <script src="{% static 'js/jquery.flot.pie.js' %}"></script>
    <script src="{% static 'js/jquery.flot.time.js' %}"></script>
    <script src="{% static 'js/jquery.flot.stack.js' %}"></script>
    <script src="{% static 'js/jquery.flot.crosshair.js' %}"></script>
    <script src="{% static 'libs/chart/jquery.peity.min.js' %}"></script>
    <script src="{% static 'libs/chart/matrix.charts.js' %}"></script>
    <script src="{% static 'libs/chart/jquery.flot.pie.min.js' %}"></script>
    <script src="{% static 'js/jquery.flot.tooltip.min.js' %}"></script>
    <script src="{% static 'libs/chart/turning-series.js' %}"></script>
    <script src="{% static 'js/chart-page-init.js' %}"></script>
</body>

</html>

templates/matrix-admin/updateVideo.html
{% extends 'matrix-admin/index2.html' %}
{% load crispy_forms_filters %}
{% block contents %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-secondary text-white">
                    <h2 class="font-weight-bold mb-0">Update Video HHHHHH</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form|crispy }}
                            <label for="id_file">Upload Video</label>
                            <input type="file" id="id_file" name="file" accept="video/*" class="form-control">
                        </div>
                        <button type="submit" class="btn btn-primary">Update Video</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock contents %}